server:
  port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/test-realm/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth2-redirect-url: http://localhost:8090/swagger-ui/oauth2-redirect.html

app:
  cors:
    allowed-origins: http://localhost:4200
